name: ui
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  csv: ^6.0.0
  file_picker: ^8.1.2
  cupertino_icons: ^1.0.8
  fl_chart: ^0.68.0
  path: ^1.8.3
  sqflite: ^2.3.0  
  path_provider: ^2.0.11
  uuid: ^4.2.1
  intl: ^0.19.0
  http: ^1.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true